FROM python:latest

# Run the Python command directly when the container starts
CMD ["python", "-c", "print('this is test')"]

# ----


# # Use the official Python image from Docker Hub
# FROM python:latest

# # Set the working directory in the container
# WORKDIR /usr/src/app

# # Copy the Python script into the container
# COPY your_script.py .

# # Run the Python script when the container launches
# CMD ["python", "your_script.py"]